# Generated by Django 2.2.2 on 2019-11-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destination_address',
            new_name='destination_text',
        ),
        migrations.RenameField(
            model_name='origin',
            old_name='origin_address',
            new_name='origin_text',
        ),
    ]
